### PR TITLE
0.4.0

### PR DESCRIPTION
**Pull request by yeahme49**
fix yt_time function
add thumbnail and channel description while searching new channels
add option to use [invidious addon](https://github.com/lekma/plugin.video.invidious) instead of youtube addon

### CODE REVIEW

**Comment by mintsoft** [comment]
Hmm, slight issue. I don't think Invidious is in the main repository, so if we put a dependency on it; you basically can't install the addon.

**Comment by yeahme49** [comment]
It's an optional dependency, so it should still install without it installed

**Comment by yeahme49** [comment]
@mintsoft Can you review this PR again? Invidious is an optional dependency so it shouldn't affect anything if you don't have that addon

**Comment by mintsoft** [comment]
@yeahme49 Yeah, sorry I got totally distracted. I'll have a look this weekend.

**Comment by mintsoft** [comment]
Cool, this looks good to me; apologies for the delay

**Comment by mintsoft** [comment]
FYI @yeahme49 https://github.com/xbmc/repo-plugins/pull/3927

**Pull request merged**
